### ISSUE TITLE
Logger : Logging filepaths, tree, repo description, ...

### ISSUE THREAD

**Issue by Aceshade** [sweepai/sweep#1211]
Hello, 

I saw in your codebase you're logging a lot of information and send it to a discord server, but I don't see the use you could have of this information. Could you clarify why you're logging all of this information ? I'm just scared this could have security issues since reassembling all of the reviews together could get information on how the system works and thus give away business logic, sensitive data, ...

For example on the review_pr file, you're logging summary, repo_description, replies, ...

  
  ```
 chat_logger = ChatLogger({
        'repo_name': repo_name,
        'title': '(Review) ' + title,
        'summary': summary + replies_text,
        "issue_url": issue_url,
        "username": username,
        "repo_description": repo_description,
        "issue_url": issue_url,
        "username": username,
        "repo_description": repo_description,
        "title": title,
        "summary": summary,
        "replies_text": replies_text,
        "tree": tree,
        "type": "review",
    })
```

Kr

**Comment by kevinlu1248** [comment]
@Aceshade The ChatLogger information is mainly for debugging and for tracking the number of GPT-4 issues used per user to decide which model to use.

In regards to debugging, when Sweep breaks and you report the bug, we can refer to the logs to figure out why Sweep errored out or underperformed. Further, these logs are only persisted for 30 days (which is also how long OpenAI stores them for).

In terms of tracking for GPT-4 issues, we use the ChatLogger to determine:
1. Whether you are a Pro, Trial, or Free tier user
2. Your remaining GPT-4 issues in the month
3. Your remaining GPT-4 issues in the day
We use this to ultimately determine which model (GPT-4 vs GPT-3.5) to give you.

We log the summary (title and body of the issue), the repo description, the issue replies etc. because they all go into the language model to curate and execute the plan.

**Comment by kevinlu1248** [comment]
Also, the Discord logger pings us with the logs of the stack traces when an error occurs. This is so we can quickly respond to let users know that we're taking a look at the error. You can trace all references of this function:

https://github.com/sweepai/sweep/blob/ba805a33b7fd7f26441ad8156dcc2f4cf0b1cfdf/sweepai/utils/chat_logger.py#L128-L137

**Comment by kevinlu1248** [comment]
@Aceshade Does this answer your question?
