### ISSUE TITLE
Sweep: Add support for using Claude as alternative to GPT-4

### ISSUE THREAD

**Issue by buger** [sweepai/sweep#1572]
### Details

While calude is not that good at coding, it has huge context. So at least can reason on top of large data. And it is 5x cheaper as well. Is it possible to switch already?

**Comment by kevinlu1248** [comment]
Hey @buger thanks for the suggestion! Unfortunately, we used to use Claude (v1.3 at the time) and had to migrate off of it because it was struggling to follow basic instructions and formatting, much less producing reasonable code. Their support was also very limited and sluggish, as well as their process for getting a commercial license. Overall we decided it was not worth trading off a quality language model and support in exchange for speed, cost and context.

We're happy to take contributions to make this an option for users though! We're just not going to focus our time on re-engineering all the prompts for Claude at this moment.

**Comment by pszemraj** [comment]
@kevinlu1248 any reconsideration possible given Claude3's performance? From quickly scanning the docs I don't see anything, so figured I'd comment here

[metrics from the blog](https://www.anthropic.com/news/claude-3-family):

![metrics](https://www.anthropic.com/_next/image?url=https%3A%2F%2Fwww-cdn.anthropic.com%2Fimages%2F4zrzovbb%2Fwebsite%2F9ad98d612086fe52b3042f9183414669b4d2a3da-2200x1954.png&w=3840&q=75)
